# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for SCAPalyzer-MCP
FROM python:3.10-slim

# Install system dependencies: sysdig for SCAP parsing
RUN apt-get update \
    && apt-get install -y --no-install-recommends sysdig \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy application code
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir requests mcp otx python-dateutil requests

# Default command: start MCP server
CMD ["python3", "server.py"]
