[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "SCAPalyzer-mcp"
version = "0.1.0"
description = "SCAP file analyzer tool to investigate captures files"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp"
]
